export const REDUX_PENDING_EFFECTS = '@@REDUX_PENDING_EFFECTS';
export const REDUX_PENDING_EFFECTS_PATCH_EFFECT =
  '@@REDUX_PENDING_EFFECTS/PATCH_EFFECT';
export const REDUX_PENDING_EFFECTS_IGNORED_ACTIONS = '@@REDUX_PENDING_EFFECTS/IGNORED_ACTIONS';
