export const patentsActionsNames = {
  GET: 'GET_PATENTS',
  PENDING: 'GET_PATENTS_PENDING',
  FULFILLED: 'GET_PATENTS_FULFILLED',
  REJECTED: 'GET_PATENTS_REJECTED'
};

export const libraryActionNames = {
  GET: 'GET_LIBRARY_CONTENT',
  PENDING: 'GET_LIBRARY_CONTENT/pending',
  FULFILLED: 'GET_LIBRARY_CONTENT/fulfilled',
  REJECTED: 'GET_LIBRARY_CONTENT/rejected'
};

export const astronomyPictureActionNames = {
  GET: 'GET_APOD',
  PENDING: 'GET_APOD_PENDING',
  FULFILLED: 'GET_APOD_FULFILLED',
  REJECTED: 'GET_APOD_REJECTED'
};

export const marsRoverPhotosActionNames = {
  GET: 'GET_MARS_ROVER_PHOTOS',
  PENDING: 'GET_MARS_ROVER_PHOTOS_PENDING',
  FULFILLED: 'GET_MARS_ROVER_PHOTOS_FULFILLED',
  REJECTED: 'GET_MARS_ROVER_PHOTOS_REJECTED'
};
